### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by cmrigney**
This should be merged in sync with the docs update.

### CODE REVIEW

**Comment by nunocoracao** [comment]
@cmrigney @craig-osterhout we can roll this and the docs out right now  - right?

**Comment by cmrigney** [comment]
@nunocoracao Doing it tomorrow: https://docker.slack.com/archives/C0316Q2HP46/p1681836213748509?thread_ts=1681835801.278129&cid=C0316Q2HP46

**Comment by cmrigney** [comment]
@nunocoracao Rolling out tomorrow.

**Comment by nunocoracao** [comment]
Thanks

**Pull request merged**
